// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"
import GeolocationController from "./geolocation_controller"
import LocationFormController from "./location_form_controller"

application.register("geolocation", GeolocationController)
application.register("location-form", LocationFormController)
