require:
  - rubocop-rails
  # - rubocop-rspec

AllCops:
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'bin/bundle'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - '.git/**/*'
    - 'tmp/**/*'
    - db/schema.rb

# RSpec/MultipleExpectations:
#   Enabled: false

# RSpec/NamedSubject:
#   Enabled: false

Layout/LineLength:
  Max: 100
  # To make it possible to copy or click on URIs in the code, we allow lines
  # containing a URI to be longer than Max.
  AllowURI: true
  URISchemes:
    - http
    - https

Metrics/BlockLength:
  CountComments: false
  Max: 25

Style/Documentation:
  Enabled: false

Style/DocumentDynamicEvalDefinition:
  Enabled: true

Rails/FilePath:
  Enabled: false

Rails/WhereNotWithMultipleConditions:
  Enabled: true

Rails/EnvironmentVariableAccess:
  Enabled: false
